### ISSUE TITLE
Over-counting dependencies?

### ISSUE THREAD

**Issue by benmccann** [NullVoxPopuli/dependency-maintainers#10]
The dependency count in the report seems quite high to me

Also, consider the comparison between these two tools. I'm not sure why they're showing different output
```
svelte$ npx dependency-maintainers | grep ljharb
│ 81      │ 'ljharb'                              │ 3          │
svelte$ npx ihimnm
None found!
```

**Comment by NullVoxPopuli** [comment]
ihimnm doesn't check peers (important due to how, by default, package-managers install them for you)

see:
- https://github.com/bluwy/ihimnm/blob/main/index.js#L60-L64
- vs: https://github.com/NullVoxPopuli/dependency-maintainers/blob/main/package-json.js#L13

See also: https://github.com/NullVoxPopuli/dependency-maintainers/issues/8#issuecomment-2187154143

**Comment by benmccann** [comment]
Hmm. I think there's some other difference. If I copy the `ihimnm` source into the `svelte` root directory and update it so that it includes `peerDependencies` it still returns "None found!"

**Comment by NullVoxPopuli** [comment]
hmm -- you could be running in to an npx cache with dependency-maintainers -- it's potentially too aggressive. Try `npx dependency-maintainers@latest` to force npx to clear its cache for dependency-maintainers

**Comment by benmccann** [comment]
Aha! That was it. Thank you!
